/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.api;

import de.tum.cit.ase.artemis.sdk.*;
import de.tum.cit.ase.artemis.sdk.auth.*;
import de.tum.cit.ase.artemis.sdk.model.GetAllTextSubmissions200ResponseInner;
import de.tum.cit.ase.artemis.sdk.model.PageableSearchDTOString;
import de.tum.cit.ase.artemis.sdk.model.SearchResultPageDTOSubmission;
import de.tum.cit.ase.artemis.sdk.model.SubmissionWithComplaintDTO;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubmissionResourceApi
 */
public class SubmissionResourceApiTest {

    private final SubmissionResourceApi api = new SubmissionResourceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSubmissionTest() throws ApiException {
        //Long id = null;
        //api.deleteSubmission(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubmissionsOnPageWithSizeTest() throws ApiException {
        //Long exerciseId = null;
        //PageableSearchDTOString search = null;
        //SearchResultPageDTOSubmission response = api.getSubmissionsOnPageWithSize(exerciseId, search);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubmissionsWithComplaintsForAssessmentDashboardTest() throws ApiException {
        //Long exerciseId = null;
        //List<SubmissionWithComplaintDTO> response = api.getSubmissionsWithComplaintsForAssessmentDashboard(exerciseId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubmissionsWithMoreFeedbackRequestForAssessmentDashboardTest() throws ApiException {
        //Long exerciseId = null;
        //List<SubmissionWithComplaintDTO> response = api.getSubmissionsWithMoreFeedbackRequestForAssessmentDashboard(exerciseId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTestRunSubmissionsForAssessmentTest() throws ApiException {
        //Long exerciseId = null;
        //List<GetAllTextSubmissions200ResponseInner> response = api.getTestRunSubmissionsForAssessment(exerciseId);
        // TODO: test validations
    }

}
