/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import de.tum.cit.ase.artemis.sdk.model.Exercise;
import de.tum.cit.ase.artemis.sdk.model.GetAllTextSubmissions200ResponseInner;
import de.tum.cit.ase.artemis.sdk.model.ProgrammingExercise;
import de.tum.cit.ase.artemis.sdk.model.ProgrammingExerciseStudentParticipation;
import de.tum.cit.ase.artemis.sdk.model.Result;
import de.tum.cit.ase.artemis.sdk.model.SolutionProgrammingExerciseParticipation;
import de.tum.cit.ase.artemis.sdk.model.StudentParticipation;
import de.tum.cit.ase.artemis.sdk.model.Team;
import de.tum.cit.ase.artemis.sdk.model.TemplateProgrammingExerciseParticipation;
import de.tum.cit.ase.artemis.sdk.model.User;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CleanupBuildPlan200Response
 */
public class CleanupBuildPlan200ResponseTest {
    private final CleanupBuildPlan200Response model = new CleanupBuildPlan200Response();

    /**
     * Model tests for CleanupBuildPlan200Response
     */
    @Test
    public void testCleanupBuildPlan200Response() {
        // TODO: test CleanupBuildPlan200Response
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'initializationState'
     */
    @Test
    public void initializationStateTest() {
        // TODO: test initializationState
    }

    /**
     * Test the property 'initializationDate'
     */
    @Test
    public void initializationDateTest() {
        // TODO: test initializationDate
    }

    /**
     * Test the property 'individualDueDate'
     */
    @Test
    public void individualDueDateTest() {
        // TODO: test individualDueDate
    }

    /**
     * Test the property 'testRun'
     */
    @Test
    public void testRunTest() {
        // TODO: test testRun
    }

    /**
     * Test the property 'exercise'
     */
    @Test
    public void exerciseTest() {
        // TODO: test exercise
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'submissions'
     */
    @Test
    public void submissionsTest() {
        // TODO: test submissions
    }

    /**
     * Test the property 'submissionCount'
     */
    @Test
    public void submissionCountTest() {
        // TODO: test submissionCount
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'presentationScore'
     */
    @Test
    public void presentationScoreTest() {
        // TODO: test presentationScore
    }

    /**
     * Test the property 'student'
     */
    @Test
    public void studentTest() {
        // TODO: test student
    }

    /**
     * Test the property 'team'
     */
    @Test
    public void teamTest() {
        // TODO: test team
    }

    /**
     * Test the property 'repositoryUrl'
     */
    @Test
    public void repositoryUrlTest() {
        // TODO: test repositoryUrl
    }

    /**
     * Test the property 'buildPlanId'
     */
    @Test
    public void buildPlanIdTest() {
        // TODO: test buildPlanId
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'userIndependentRepositoryUrl'
     */
    @Test
    public void userIndependentRepositoryUrlTest() {
        // TODO: test userIndependentRepositoryUrl
    }

    /**
     * Test the property 'participantIdentifier'
     */
    @Test
    public void participantIdentifierTest() {
        // TODO: test participantIdentifier
    }

    /**
     * Test the property 'participantName'
     */
    @Test
    public void participantNameTest() {
        // TODO: test participantName
    }

    /**
     * Test the property 'programmingExercise'
     */
    @Test
    public void programmingExerciseTest() {
        // TODO: test programmingExercise
    }

}
