/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import de.tum.cit.ase.artemis.sdk.model.Exam;
import de.tum.cit.ase.artemis.sdk.model.GetExercise200Response;
import de.tum.cit.ase.artemis.sdk.model.Lecture;
import de.tum.cit.ase.artemis.sdk.model.OnlineCourseConfiguration;
import de.tum.cit.ase.artemis.sdk.model.Organization;
import de.tum.cit.ase.artemis.sdk.model.Post;
import de.tum.cit.ase.artemis.sdk.model.TutorialGroup;
import de.tum.cit.ase.artemis.sdk.model.TutorialGroupsConfiguration;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Course
 */
public class CourseTest {
    private final Course model = new Course();

    /**
     * Model tests for Course
     */
    @Test
    public void testCourse() {
        // TODO: test Course
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'shortName'
     */
    @Test
    public void shortNameTest() {
        // TODO: test shortName
    }

    /**
     * Test the property 'studentGroupName'
     */
    @Test
    public void studentGroupNameTest() {
        // TODO: test studentGroupName
    }

    /**
     * Test the property 'teachingAssistantGroupName'
     */
    @Test
    public void teachingAssistantGroupNameTest() {
        // TODO: test teachingAssistantGroupName
    }

    /**
     * Test the property 'editorGroupName'
     */
    @Test
    public void editorGroupNameTest() {
        // TODO: test editorGroupName
    }

    /**
     * Test the property 'instructorGroupName'
     */
    @Test
    public void instructorGroupNameTest() {
        // TODO: test instructorGroupName
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'semester'
     */
    @Test
    public void semesterTest() {
        // TODO: test semester
    }

    /**
     * Test the property 'testCourse'
     */
    @Test
    public void testCourseTest() {
        // TODO: test testCourse
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'defaultProgrammingLanguage'
     */
    @Test
    public void defaultProgrammingLanguageTest() {
        // TODO: test defaultProgrammingLanguage
    }

    /**
     * Test the property 'onlineCourse'
     */
    @Test
    public void onlineCourseTest() {
        // TODO: test onlineCourse
    }

    /**
     * Test the property 'onlineCourseConfiguration'
     */
    @Test
    public void onlineCourseConfigurationTest() {
        // TODO: test onlineCourseConfiguration
    }

    /**
     * Test the property 'maxComplaints'
     */
    @Test
    public void maxComplaintsTest() {
        // TODO: test maxComplaints
    }

    /**
     * Test the property 'maxTeamComplaints'
     */
    @Test
    public void maxTeamComplaintsTest() {
        // TODO: test maxTeamComplaints
    }

    /**
     * Test the property 'maxComplaintTimeDays'
     */
    @Test
    public void maxComplaintTimeDaysTest() {
        // TODO: test maxComplaintTimeDays
    }

    /**
     * Test the property 'maxRequestMoreFeedbackTimeDays'
     */
    @Test
    public void maxRequestMoreFeedbackTimeDaysTest() {
        // TODO: test maxRequestMoreFeedbackTimeDays
    }

    /**
     * Test the property 'maxComplaintTextLimit'
     */
    @Test
    public void maxComplaintTextLimitTest() {
        // TODO: test maxComplaintTextLimit
    }

    /**
     * Test the property 'maxComplaintResponseTextLimit'
     */
    @Test
    public void maxComplaintResponseTextLimitTest() {
        // TODO: test maxComplaintResponseTextLimit
    }

    /**
     * Test the property 'postsEnabled'
     */
    @Test
    public void postsEnabledTest() {
        // TODO: test postsEnabled
    }

    /**
     * Test the property 'posts'
     */
    @Test
    public void postsTest() {
        // TODO: test posts
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'courseIcon'
     */
    @Test
    public void courseIconTest() {
        // TODO: test courseIcon
    }

    /**
     * Test the property 'registrationEnabled'
     */
    @Test
    public void registrationEnabledTest() {
        // TODO: test registrationEnabled
    }

    /**
     * Test the property 'registrationConfirmationMessage'
     */
    @Test
    public void registrationConfirmationMessageTest() {
        // TODO: test registrationConfirmationMessage
    }

    /**
     * Test the property 'presentationScore'
     */
    @Test
    public void presentationScoreTest() {
        // TODO: test presentationScore
    }

    /**
     * Test the property 'courseArchivePath'
     */
    @Test
    public void courseArchivePathTest() {
        // TODO: test courseArchivePath
    }

    /**
     * Test the property 'maxPoints'
     */
    @Test
    public void maxPointsTest() {
        // TODO: test maxPoints
    }

    /**
     * Test the property 'accuracyOfScores'
     */
    @Test
    public void accuracyOfScoresTest() {
        // TODO: test accuracyOfScores
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

    /**
     * Test the property 'exercises'
     */
    @Test
    public void exercisesTest() {
        // TODO: test exercises
    }

    /**
     * Test the property 'lectures'
     */
    @Test
    public void lecturesTest() {
        // TODO: test lectures
    }

    /**
     * Test the property 'tutorialGroups'
     */
    @Test
    public void tutorialGroupsTest() {
        // TODO: test tutorialGroups
    }

    /**
     * Test the property 'exams'
     */
    @Test
    public void examsTest() {
        // TODO: test exams
    }

    /**
     * Test the property 'organizations'
     */
    @Test
    public void organizationsTest() {
        // TODO: test organizations
    }

    /**
     * Test the property 'tutorialGroupsConfiguration'
     */
    @Test
    public void tutorialGroupsConfigurationTest() {
        // TODO: test tutorialGroupsConfiguration
    }

    /**
     * Test the property 'requestMoreFeedbackEnabled'
     */
    @Test
    public void requestMoreFeedbackEnabledTest() {
        // TODO: test requestMoreFeedbackEnabled
    }

    /**
     * Test the property 'complaintsEnabled'
     */
    @Test
    public void complaintsEnabledTest() {
        // TODO: test complaintsEnabled
    }

    /**
     * Test the property 'validStartAndEndDate'
     */
    @Test
    public void validStartAndEndDateTest() {
        // TODO: test validStartAndEndDate
    }

    /**
     * Test the property 'numberOfInstructors'
     */
    @Test
    public void numberOfInstructorsTest() {
        // TODO: test numberOfInstructors
    }

    /**
     * Test the property 'numberOfTeachingAssistants'
     */
    @Test
    public void numberOfTeachingAssistantsTest() {
        // TODO: test numberOfTeachingAssistants
    }

    /**
     * Test the property 'numberOfEditors'
     */
    @Test
    public void numberOfEditorsTest() {
        // TODO: test numberOfEditors
    }

    /**
     * Test the property 'numberOfStudents'
     */
    @Test
    public void numberOfStudentsTest() {
        // TODO: test numberOfStudents
    }

}
