/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import de.tum.cit.ase.artemis.sdk.model.PlagiarismComparisonModelingSubmissionElement;
import java.util.LinkedHashSet;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelingPlagiarismResultAllOf
 */
public class ModelingPlagiarismResultAllOfTest {
    private final ModelingPlagiarismResultAllOf model = new ModelingPlagiarismResultAllOf();

    /**
     * Model tests for ModelingPlagiarismResultAllOf
     */
    @Test
    public void testModelingPlagiarismResultAllOf() {
        // TODO: test ModelingPlagiarismResultAllOf
    }

    /**
     * Test the property 'comparisons'
     */
    @Test
    public void comparisonsTest() {
        // TODO: test comparisons
    }

}
