/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import de.tum.cit.ase.artemis.sdk.model.PlagiarismMatch;
import de.tum.cit.ase.artemis.sdk.model.PlagiarismResultObject;
import java.util.LinkedHashSet;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlagiarismComparisonObject
 */
public class PlagiarismComparisonObjectTest {
    private final PlagiarismComparisonObject model = new PlagiarismComparisonObject();

    /**
     * Model tests for PlagiarismComparisonObject
     */
    @Test
    public void testPlagiarismComparisonObject() {
        // TODO: test PlagiarismComparisonObject
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'plagiarismResult'
     */
    @Test
    public void plagiarismResultTest() {
        // TODO: test plagiarismResult
    }

    /**
     * Test the property 'matches'
     */
    @Test
    public void matchesTest() {
        // TODO: test matches
    }

    /**
     * Test the property 'similarity'
     */
    @Test
    public void similarityTest() {
        // TODO: test similarity
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
