/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProgrammingExerciseTestCaseDTO
 */
public class ProgrammingExerciseTestCaseDTOTest {
    private final ProgrammingExerciseTestCaseDTO model = new ProgrammingExerciseTestCaseDTO();

    /**
     * Model tests for ProgrammingExerciseTestCaseDTO
     */
    @Test
    public void testProgrammingExerciseTestCaseDTO() {
        // TODO: test ProgrammingExerciseTestCaseDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'bonusMultiplier'
     */
    @Test
    public void bonusMultiplierTest() {
        // TODO: test bonusMultiplier
    }

    /**
     * Test the property 'bonusPoints'
     */
    @Test
    public void bonusPointsTest() {
        // TODO: test bonusPoints
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

}
