/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.cit.ase.artemis.sdk.model.CleanupBuildPlan200Response;
import de.tum.cit.ase.artemis.sdk.model.CoverageFileReport;
import de.tum.cit.ase.artemis.sdk.model.Feedback;
import de.tum.cit.ase.artemis.sdk.model.GetAllTextSubmissions200ResponseInner;
import de.tum.cit.ase.artemis.sdk.model.User;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Result
 */
public class ResultTest {
    private final Result model = new Result();

    /**
     * Model tests for Result
     */
    @Test
    public void testResult() {
        // TODO: test Result
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'completionDate'
     */
    @Test
    public void completionDateTest() {
        // TODO: test completionDate
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'score'
     */
    @Test
    public void scoreTest() {
        // TODO: test score
    }

    /**
     * Test the property 'rated'
     */
    @Test
    public void ratedTest() {
        // TODO: test rated
    }

    /**
     * Test the property 'submission'
     */
    @Test
    public void submissionTest() {
        // TODO: test submission
    }

    /**
     * Test the property 'feedbacks'
     */
    @Test
    public void feedbacksTest() {
        // TODO: test feedbacks
    }

    /**
     * Test the property 'participation'
     */
    @Test
    public void participationTest() {
        // TODO: test participation
    }

    /**
     * Test the property 'assessor'
     */
    @Test
    public void assessorTest() {
        // TODO: test assessor
    }

    /**
     * Test the property 'assessmentType'
     */
    @Test
    public void assessmentTypeTest() {
        // TODO: test assessmentType
    }

    /**
     * Test the property 'hasComplaint'
     */
    @Test
    public void hasComplaintTest() {
        // TODO: test hasComplaint
    }

    /**
     * Test the property 'exampleResult'
     */
    @Test
    public void exampleResultTest() {
        // TODO: test exampleResult
    }

    /**
     * Test the property 'testCaseCount'
     */
    @Test
    public void testCaseCountTest() {
        // TODO: test testCaseCount
    }

    /**
     * Test the property 'passedTestCaseCount'
     */
    @Test
    public void passedTestCaseCountTest() {
        // TODO: test passedTestCaseCount
    }

    /**
     * Test the property 'codeIssueCount'
     */
    @Test
    public void codeIssueCountTest() {
        // TODO: test codeIssueCount
    }

    /**
     * Test the property 'coverageFileReportsByTestCaseName'
     */
    @Test
    public void coverageFileReportsByTestCaseNameTest() {
        // TODO: test coverageFileReportsByTestCaseName
    }

    /**
     * Test the property 'feedbackType'
     */
    @Test
    public void feedbackTypeTest() {
        // TODO: test feedbackType
    }

}
