/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.cit.ase.artemis.sdk.model.Applinks;
import de.tum.cit.ase.artemis.sdk.model.Webcredentials;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import de.tum.cit.ase.artemis.sdk.JSON;


/**
 * AppleAppSiteAssociation
 */
@JsonPropertyOrder({
  AppleAppSiteAssociation.JSON_PROPERTY_APPLINKS,
  AppleAppSiteAssociation.JSON_PROPERTY_WEBCREDENTIALS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-10T14:33:20.156837Z[Etc/UTC]")
public class AppleAppSiteAssociation {
  public static final String JSON_PROPERTY_APPLINKS = "applinks";
  private Applinks applinks;

  public static final String JSON_PROPERTY_WEBCREDENTIALS = "webcredentials";
  private Webcredentials webcredentials;

  public AppleAppSiteAssociation() { 
  }

  public AppleAppSiteAssociation applinks(Applinks applinks) {
    this.applinks = applinks;
    return this;
  }

   /**
   * Get applinks
   * @return applinks
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPLINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Applinks getApplinks() {
    return applinks;
  }


  @JsonProperty(JSON_PROPERTY_APPLINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplinks(Applinks applinks) {
    this.applinks = applinks;
  }


  public AppleAppSiteAssociation webcredentials(Webcredentials webcredentials) {
    this.webcredentials = webcredentials;
    return this;
  }

   /**
   * Get webcredentials
   * @return webcredentials
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBCREDENTIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Webcredentials getWebcredentials() {
    return webcredentials;
  }


  @JsonProperty(JSON_PROPERTY_WEBCREDENTIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebcredentials(Webcredentials webcredentials) {
    this.webcredentials = webcredentials;
  }


  /**
   * Return true if this AppleAppSiteAssociation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppleAppSiteAssociation appleAppSiteAssociation = (AppleAppSiteAssociation) o;
    return Objects.equals(this.applinks, appleAppSiteAssociation.applinks) &&
        Objects.equals(this.webcredentials, appleAppSiteAssociation.webcredentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applinks, webcredentials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppleAppSiteAssociation {\n");
    sb.append("    applinks: ").append(toIndentedString(applinks)).append("\n");
    sb.append("    webcredentials: ").append(toIndentedString(webcredentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

