/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import de.tum.cit.ase.artemis.sdk.JSON;


/**
 * PageableSearchDTOString
 */
@JsonPropertyOrder({
  PageableSearchDTOString.JSON_PROPERTY_PAGE,
  PageableSearchDTOString.JSON_PROPERTY_PAGE_SIZE,
  PageableSearchDTOString.JSON_PROPERTY_SEARCH_TERM,
  PageableSearchDTOString.JSON_PROPERTY_SORTING_ORDER,
  PageableSearchDTOString.JSON_PROPERTY_SORTED_COLUMN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-10T14:33:20.156837Z[Etc/UTC]")
public class PageableSearchDTOString {
  public static final String JSON_PROPERTY_PAGE = "page";
  private Integer page;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  private Integer pageSize;

  public static final String JSON_PROPERTY_SEARCH_TERM = "searchTerm";
  private String searchTerm;

  /**
   * Gets or Sets sortingOrder
   */
  public enum SortingOrderEnum {
    ASCENDING("ASCENDING"),
    
    DESCENDING("DESCENDING");

    private String value;

    SortingOrderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SortingOrderEnum fromValue(String value) {
      for (SortingOrderEnum b : SortingOrderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SORTING_ORDER = "sortingOrder";
  private SortingOrderEnum sortingOrder;

  public static final String JSON_PROPERTY_SORTED_COLUMN = "sortedColumn";
  private String sortedColumn;

  public PageableSearchDTOString() { 
  }

  public PageableSearchDTOString page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(Integer page) {
    this.page = page;
  }


  public PageableSearchDTOString pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  public PageableSearchDTOString searchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
    return this;
  }

   /**
   * Get searchTerm
   * @return searchTerm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEARCH_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSearchTerm() {
    return searchTerm;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
  }


  public PageableSearchDTOString sortingOrder(SortingOrderEnum sortingOrder) {
    this.sortingOrder = sortingOrder;
    return this;
  }

   /**
   * Get sortingOrder
   * @return sortingOrder
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORTING_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SortingOrderEnum getSortingOrder() {
    return sortingOrder;
  }


  @JsonProperty(JSON_PROPERTY_SORTING_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortingOrder(SortingOrderEnum sortingOrder) {
    this.sortingOrder = sortingOrder;
  }


  public PageableSearchDTOString sortedColumn(String sortedColumn) {
    this.sortedColumn = sortedColumn;
    return this;
  }

   /**
   * Get sortedColumn
   * @return sortedColumn
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORTED_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSortedColumn() {
    return sortedColumn;
  }


  @JsonProperty(JSON_PROPERTY_SORTED_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortedColumn(String sortedColumn) {
    this.sortedColumn = sortedColumn;
  }


  /**
   * Return true if this PageableSearchDTOString object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageableSearchDTOString pageableSearchDTOString = (PageableSearchDTOString) o;
    return Objects.equals(this.page, pageableSearchDTOString.page) &&
        Objects.equals(this.pageSize, pageableSearchDTOString.pageSize) &&
        Objects.equals(this.searchTerm, pageableSearchDTOString.searchTerm) &&
        Objects.equals(this.sortingOrder, pageableSearchDTOString.sortingOrder) &&
        Objects.equals(this.sortedColumn, pageableSearchDTOString.sortedColumn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, pageSize, searchTerm, sortingOrder, sortedColumn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageableSearchDTOString {\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    searchTerm: ").append(toIndentedString(searchTerm)).append("\n");
    sb.append("    sortingOrder: ").append(toIndentedString(sortingOrder)).append("\n");
    sb.append("    sortedColumn: ").append(toIndentedString(sortedColumn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

