/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BuildLogStatisticsDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-19T16:35:01.729286Z[Etc/UTC]")
public class BuildLogStatisticsDTO {
  public static final String SERIALIZED_NAME_BUILD_COUNT = "buildCount";
  @SerializedName(SERIALIZED_NAME_BUILD_COUNT)
  private Long buildCount;

  public static final String SERIALIZED_NAME_AGENT_SETUP_DURATION = "agentSetupDuration";
  @SerializedName(SERIALIZED_NAME_AGENT_SETUP_DURATION)
  private Double agentSetupDuration;

  public static final String SERIALIZED_NAME_TEST_DURATION = "testDuration";
  @SerializedName(SERIALIZED_NAME_TEST_DURATION)
  private Double testDuration;

  public static final String SERIALIZED_NAME_SCA_DURATION = "scaDuration";
  @SerializedName(SERIALIZED_NAME_SCA_DURATION)
  private Double scaDuration;

  public static final String SERIALIZED_NAME_TOTAL_JOB_DURATION = "totalJobDuration";
  @SerializedName(SERIALIZED_NAME_TOTAL_JOB_DURATION)
  private Double totalJobDuration;

  public static final String SERIALIZED_NAME_DEPENDENCIES_DOWNLOADED_COUNT = "dependenciesDownloadedCount";
  @SerializedName(SERIALIZED_NAME_DEPENDENCIES_DOWNLOADED_COUNT)
  private Double dependenciesDownloadedCount;

  public BuildLogStatisticsDTO() {
  }

  public BuildLogStatisticsDTO buildCount(Long buildCount) {
    
    this.buildCount = buildCount;
    return this;
  }

   /**
   * Get buildCount
   * @return buildCount
  **/
  @javax.annotation.Nullable

  public Long getBuildCount() {
    return buildCount;
  }


  public void setBuildCount(Long buildCount) {
    this.buildCount = buildCount;
  }


  public BuildLogStatisticsDTO agentSetupDuration(Double agentSetupDuration) {
    
    this.agentSetupDuration = agentSetupDuration;
    return this;
  }

   /**
   * Get agentSetupDuration
   * @return agentSetupDuration
  **/
  @javax.annotation.Nullable

  public Double getAgentSetupDuration() {
    return agentSetupDuration;
  }


  public void setAgentSetupDuration(Double agentSetupDuration) {
    this.agentSetupDuration = agentSetupDuration;
  }


  public BuildLogStatisticsDTO testDuration(Double testDuration) {
    
    this.testDuration = testDuration;
    return this;
  }

   /**
   * Get testDuration
   * @return testDuration
  **/
  @javax.annotation.Nullable

  public Double getTestDuration() {
    return testDuration;
  }


  public void setTestDuration(Double testDuration) {
    this.testDuration = testDuration;
  }


  public BuildLogStatisticsDTO scaDuration(Double scaDuration) {
    
    this.scaDuration = scaDuration;
    return this;
  }

   /**
   * Get scaDuration
   * @return scaDuration
  **/
  @javax.annotation.Nullable

  public Double getScaDuration() {
    return scaDuration;
  }


  public void setScaDuration(Double scaDuration) {
    this.scaDuration = scaDuration;
  }


  public BuildLogStatisticsDTO totalJobDuration(Double totalJobDuration) {
    
    this.totalJobDuration = totalJobDuration;
    return this;
  }

   /**
   * Get totalJobDuration
   * @return totalJobDuration
  **/
  @javax.annotation.Nullable

  public Double getTotalJobDuration() {
    return totalJobDuration;
  }


  public void setTotalJobDuration(Double totalJobDuration) {
    this.totalJobDuration = totalJobDuration;
  }


  public BuildLogStatisticsDTO dependenciesDownloadedCount(Double dependenciesDownloadedCount) {
    
    this.dependenciesDownloadedCount = dependenciesDownloadedCount;
    return this;
  }

   /**
   * Get dependenciesDownloadedCount
   * @return dependenciesDownloadedCount
  **/
  @javax.annotation.Nullable

  public Double getDependenciesDownloadedCount() {
    return dependenciesDownloadedCount;
  }


  public void setDependenciesDownloadedCount(Double dependenciesDownloadedCount) {
    this.dependenciesDownloadedCount = dependenciesDownloadedCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildLogStatisticsDTO buildLogStatisticsDTO = (BuildLogStatisticsDTO) o;
    return Objects.equals(this.buildCount, buildLogStatisticsDTO.buildCount) &&
        Objects.equals(this.agentSetupDuration, buildLogStatisticsDTO.agentSetupDuration) &&
        Objects.equals(this.testDuration, buildLogStatisticsDTO.testDuration) &&
        Objects.equals(this.scaDuration, buildLogStatisticsDTO.scaDuration) &&
        Objects.equals(this.totalJobDuration, buildLogStatisticsDTO.totalJobDuration) &&
        Objects.equals(this.dependenciesDownloadedCount, buildLogStatisticsDTO.dependenciesDownloadedCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildCount, agentSetupDuration, testDuration, scaDuration, totalJobDuration, dependenciesDownloadedCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildLogStatisticsDTO {\n");
    sb.append("    buildCount: ").append(toIndentedString(buildCount)).append("\n");
    sb.append("    agentSetupDuration: ").append(toIndentedString(agentSetupDuration)).append("\n");
    sb.append("    testDuration: ").append(toIndentedString(testDuration)).append("\n");
    sb.append("    scaDuration: ").append(toIndentedString(scaDuration)).append("\n");
    sb.append("    totalJobDuration: ").append(toIndentedString(totalJobDuration)).append("\n");
    sb.append("    dependenciesDownloadedCount: ").append(toIndentedString(dependenciesDownloadedCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("buildCount");
    openapiFields.add("agentSetupDuration");
    openapiFields.add("testDuration");
    openapiFields.add("scaDuration");
    openapiFields.add("totalJobDuration");
    openapiFields.add("dependenciesDownloadedCount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BuildLogStatisticsDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BuildLogStatisticsDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BuildLogStatisticsDTO is not found in the empty JSON string", BuildLogStatisticsDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BuildLogStatisticsDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BuildLogStatisticsDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BuildLogStatisticsDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BuildLogStatisticsDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BuildLogStatisticsDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BuildLogStatisticsDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<BuildLogStatisticsDTO>() {
           @Override
           public void write(JsonWriter out, BuildLogStatisticsDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BuildLogStatisticsDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BuildLogStatisticsDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BuildLogStatisticsDTO
  * @throws IOException if the JSON string is invalid with respect to BuildLogStatisticsDTO
  */
  public static BuildLogStatisticsDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BuildLogStatisticsDTO.class);
  }

 /**
  * Convert an instance of BuildLogStatisticsDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

