/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ExamInformationDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-19T16:35:01.729286Z[Etc/UTC]")
public class ExamInformationDTO {
  public static final String SERIALIZED_NAME_LATEST_INDIVIDUAL_END_DATE = "latestIndividualEndDate";
  @SerializedName(SERIALIZED_NAME_LATEST_INDIVIDUAL_END_DATE)
  private OffsetDateTime latestIndividualEndDate;

  public ExamInformationDTO() {
  }

  public ExamInformationDTO latestIndividualEndDate(OffsetDateTime latestIndividualEndDate) {
    
    this.latestIndividualEndDate = latestIndividualEndDate;
    return this;
  }

   /**
   * Get latestIndividualEndDate
   * @return latestIndividualEndDate
  **/
  @javax.annotation.Nullable

  public OffsetDateTime getLatestIndividualEndDate() {
    return latestIndividualEndDate;
  }


  public void setLatestIndividualEndDate(OffsetDateTime latestIndividualEndDate) {
    this.latestIndividualEndDate = latestIndividualEndDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExamInformationDTO examInformationDTO = (ExamInformationDTO) o;
    return Objects.equals(this.latestIndividualEndDate, examInformationDTO.latestIndividualEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latestIndividualEndDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExamInformationDTO {\n");
    sb.append("    latestIndividualEndDate: ").append(toIndentedString(latestIndividualEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("latestIndividualEndDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExamInformationDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExamInformationDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExamInformationDTO is not found in the empty JSON string", ExamInformationDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ExamInformationDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExamInformationDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExamInformationDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExamInformationDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExamInformationDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExamInformationDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ExamInformationDTO>() {
           @Override
           public void write(JsonWriter out, ExamInformationDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExamInformationDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExamInformationDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExamInformationDTO
  * @throws IOException if the JSON string is invalid with respect to ExamInformationDTO
  */
  public static ExamInformationDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExamInformationDTO.class);
  }

 /**
  * Convert an instance of ExamInformationDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

