/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Course;
import org.openapitools.client.model.GroupNotification;
import org.openapitools.client.model.NotificationTarget;
import org.openapitools.client.model.SingleUserNotification;
import org.openapitools.client.model.SystemNotification;
import org.openapitools.client.model.User;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-19T16:35:01.729286Z[Etc/UTC]")
public class GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GroupNotification> adapterGroupNotification = gson.getDelegateAdapter(this, TypeToken.get(GroupNotification.class));
            final TypeAdapter<SingleUserNotification> adapterSingleUserNotification = gson.getDelegateAdapter(this, TypeToken.get(SingleUserNotification.class));
            final TypeAdapter<SystemNotification> adapterSystemNotification = gson.getDelegateAdapter(this, TypeToken.get(SystemNotification.class));

            return (TypeAdapter<T>) new TypeAdapter<GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner>() {
                @Override
                public void write(JsonWriter out, GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `GroupNotification`
                    if (value.getActualInstance() instanceof GroupNotification) {
                        JsonObject obj = adapterGroupNotification.toJsonTree((GroupNotification)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SingleUserNotification`
                    if (value.getActualInstance() instanceof SingleUserNotification) {
                        JsonObject obj = adapterSingleUserNotification.toJsonTree((SingleUserNotification)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `SystemNotification`
                    if (value.getActualInstance() instanceof SystemNotification) {
                        JsonObject obj = adapterSystemNotification.toJsonTree((SystemNotification)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: GroupNotification, SingleUserNotification, SystemNotification");
                }

                @Override
                public GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize GroupNotification
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GroupNotification.validateJsonObject(jsonObject);
                        actualAdapter = adapterGroupNotification;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'GroupNotification'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for GroupNotification failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GroupNotification'", e);
                    }

                    // deserialize SingleUserNotification
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SingleUserNotification.validateJsonObject(jsonObject);
                        actualAdapter = adapterSingleUserNotification;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SingleUserNotification'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SingleUserNotification failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SingleUserNotification'", e);
                    }

                    // deserialize SystemNotification
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SystemNotification.validateJsonObject(jsonObject);
                        actualAdapter = adapterSystemNotification;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'SystemNotification'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for SystemNotification failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SystemNotification'", e);
                    }

                    if (match == 1) {
                        GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner ret = new GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonObject));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner() {
        super("oneOf", Boolean.FALSE);
    }

    public GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner(GroupNotification o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner(SingleUserNotification o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner(SystemNotification o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GroupNotification", new GenericType<GroupNotification>() {
        });
        schemas.put("SingleUserNotification", new GenericType<SingleUserNotification>() {
        });
        schemas.put("SystemNotification", new GenericType<SystemNotification>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * GroupNotification, SingleUserNotification, SystemNotification
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof GroupNotification) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SingleUserNotification) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SystemNotification) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GroupNotification, SingleUserNotification, SystemNotification");
    }

    /**
     * Get the actual instance, which can be the following:
     * GroupNotification, SingleUserNotification, SystemNotification
     *
     * @return The actual instance (GroupNotification, SingleUserNotification, SystemNotification)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GroupNotification`. If the actual instance is not `GroupNotification`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GroupNotification`
     * @throws ClassCastException if the instance is not `GroupNotification`
     */
    public GroupNotification getGroupNotification() throws ClassCastException {
        return (GroupNotification)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SingleUserNotification`. If the actual instance is not `SingleUserNotification`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SingleUserNotification`
     * @throws ClassCastException if the instance is not `SingleUserNotification`
     */
    public SingleUserNotification getSingleUserNotification() throws ClassCastException {
        return (SingleUserNotification)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SystemNotification`. If the actual instance is not `SystemNotification`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SystemNotification`
     * @throws ClassCastException if the instance is not `SystemNotification`
     */
    public SystemNotification getSystemNotification() throws ClassCastException {
        return (SystemNotification)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with GroupNotification
    try {
      GroupNotification.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for GroupNotification failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SingleUserNotification
    try {
      SingleUserNotification.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SingleUserNotification failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SystemNotification
    try {
      SystemNotification.validateJsonObject(jsonObj);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SystemNotification failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner with oneOf schemas: GroupNotification, SingleUserNotification, SystemNotification. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonObj.toString()));
    }
  }

 /**
  * Create an instance of GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner
  * @throws IOException if the JSON string is invalid with respect to GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner
  */
  public static GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner.class);
  }

 /**
  * Convert an instance of GetAllNotificationsForCurrentUserFilteredBySettings200ResponseInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

