/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SubmissionExportOptionsDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-19T16:35:01.729286Z[Etc/UTC]")
public class SubmissionExportOptionsDTO {
  public static final String SERIALIZED_NAME_EXPORT_ALL_PARTICIPANTS = "exportAllParticipants";
  @SerializedName(SERIALIZED_NAME_EXPORT_ALL_PARTICIPANTS)
  private Boolean exportAllParticipants;

  public static final String SERIALIZED_NAME_FILTER_LATE_SUBMISSIONS = "filterLateSubmissions";
  @SerializedName(SERIALIZED_NAME_FILTER_LATE_SUBMISSIONS)
  private Boolean filterLateSubmissions;

  public static final String SERIALIZED_NAME_FILTER_LATE_SUBMISSIONS_DATE = "filterLateSubmissionsDate";
  @SerializedName(SERIALIZED_NAME_FILTER_LATE_SUBMISSIONS_DATE)
  private OffsetDateTime filterLateSubmissionsDate;

  public static final String SERIALIZED_NAME_PARTICIPANT_IDENTIFIER_LIST = "participantIdentifierList";
  @SerializedName(SERIALIZED_NAME_PARTICIPANT_IDENTIFIER_LIST)
  private String participantIdentifierList;

  public SubmissionExportOptionsDTO() {
  }

  public SubmissionExportOptionsDTO exportAllParticipants(Boolean exportAllParticipants) {
    
    this.exportAllParticipants = exportAllParticipants;
    return this;
  }

   /**
   * Get exportAllParticipants
   * @return exportAllParticipants
  **/
  @javax.annotation.Nullable

  public Boolean getExportAllParticipants() {
    return exportAllParticipants;
  }


  public void setExportAllParticipants(Boolean exportAllParticipants) {
    this.exportAllParticipants = exportAllParticipants;
  }


  public SubmissionExportOptionsDTO filterLateSubmissions(Boolean filterLateSubmissions) {
    
    this.filterLateSubmissions = filterLateSubmissions;
    return this;
  }

   /**
   * Get filterLateSubmissions
   * @return filterLateSubmissions
  **/
  @javax.annotation.Nullable

  public Boolean getFilterLateSubmissions() {
    return filterLateSubmissions;
  }


  public void setFilterLateSubmissions(Boolean filterLateSubmissions) {
    this.filterLateSubmissions = filterLateSubmissions;
  }


  public SubmissionExportOptionsDTO filterLateSubmissionsDate(OffsetDateTime filterLateSubmissionsDate) {
    
    this.filterLateSubmissionsDate = filterLateSubmissionsDate;
    return this;
  }

   /**
   * Get filterLateSubmissionsDate
   * @return filterLateSubmissionsDate
  **/
  @javax.annotation.Nullable

  public OffsetDateTime getFilterLateSubmissionsDate() {
    return filterLateSubmissionsDate;
  }


  public void setFilterLateSubmissionsDate(OffsetDateTime filterLateSubmissionsDate) {
    this.filterLateSubmissionsDate = filterLateSubmissionsDate;
  }


  public SubmissionExportOptionsDTO participantIdentifierList(String participantIdentifierList) {
    
    this.participantIdentifierList = participantIdentifierList;
    return this;
  }

   /**
   * Get participantIdentifierList
   * @return participantIdentifierList
  **/
  @javax.annotation.Nullable

  public String getParticipantIdentifierList() {
    return participantIdentifierList;
  }


  public void setParticipantIdentifierList(String participantIdentifierList) {
    this.participantIdentifierList = participantIdentifierList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmissionExportOptionsDTO submissionExportOptionsDTO = (SubmissionExportOptionsDTO) o;
    return Objects.equals(this.exportAllParticipants, submissionExportOptionsDTO.exportAllParticipants) &&
        Objects.equals(this.filterLateSubmissions, submissionExportOptionsDTO.filterLateSubmissions) &&
        Objects.equals(this.filterLateSubmissionsDate, submissionExportOptionsDTO.filterLateSubmissionsDate) &&
        Objects.equals(this.participantIdentifierList, submissionExportOptionsDTO.participantIdentifierList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportAllParticipants, filterLateSubmissions, filterLateSubmissionsDate, participantIdentifierList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmissionExportOptionsDTO {\n");
    sb.append("    exportAllParticipants: ").append(toIndentedString(exportAllParticipants)).append("\n");
    sb.append("    filterLateSubmissions: ").append(toIndentedString(filterLateSubmissions)).append("\n");
    sb.append("    filterLateSubmissionsDate: ").append(toIndentedString(filterLateSubmissionsDate)).append("\n");
    sb.append("    participantIdentifierList: ").append(toIndentedString(participantIdentifierList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("exportAllParticipants");
    openapiFields.add("filterLateSubmissions");
    openapiFields.add("filterLateSubmissionsDate");
    openapiFields.add("participantIdentifierList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SubmissionExportOptionsDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SubmissionExportOptionsDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubmissionExportOptionsDTO is not found in the empty JSON string", SubmissionExportOptionsDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SubmissionExportOptionsDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubmissionExportOptionsDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("participantIdentifierList") != null && !jsonObj.get("participantIdentifierList").isJsonNull()) && !jsonObj.get("participantIdentifierList").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `participantIdentifierList` to be a primitive type in the JSON string but got `%s`", jsonObj.get("participantIdentifierList").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmissionExportOptionsDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmissionExportOptionsDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmissionExportOptionsDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmissionExportOptionsDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmissionExportOptionsDTO>() {
           @Override
           public void write(JsonWriter out, SubmissionExportOptionsDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmissionExportOptionsDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SubmissionExportOptionsDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SubmissionExportOptionsDTO
  * @throws IOException if the JSON string is invalid with respect to SubmissionExportOptionsDTO
  */
  public static SubmissionExportOptionsDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmissionExportOptionsDTO.class);
  }

 /**
  * Convert an instance of SubmissionExportOptionsDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

