/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChannelDTOAllOf
 */
public class ChannelDTOAllOfTest {
    private final ChannelDTOAllOf model = new ChannelDTOAllOf();

    /**
     * Model tests for ChannelDTOAllOf
     */
    @Test
    public void testChannelDTOAllOf() {
        // TODO: test ChannelDTOAllOf
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'topic'
     */
    @Test
    public void topicTest() {
        // TODO: test topic
    }

    /**
     * Test the property 'isPublic'
     */
    @Test
    public void isPublicTest() {
        // TODO: test isPublic
    }

    /**
     * Test the property 'isAnnouncementChannel'
     */
    @Test
    public void isAnnouncementChannelTest() {
        // TODO: test isAnnouncementChannel
    }

    /**
     * Test the property 'isArchived'
     */
    @Test
    public void isArchivedTest() {
        // TODO: test isArchived
    }

    /**
     * Test the property 'hasChannelModerationRights'
     */
    @Test
    public void hasChannelModerationRightsTest() {
        // TODO: test hasChannelModerationRights
    }

    /**
     * Test the property 'isChannelModerator'
     */
    @Test
    public void isChannelModeratorTest() {
        // TODO: test isChannelModerator
    }

}
