/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ParticipantScoreAverageDTO
 */
public class ParticipantScoreAverageDTOTest {
    private final ParticipantScoreAverageDTO model = new ParticipantScoreAverageDTO();

    /**
     * Model tests for ParticipantScoreAverageDTO
     */
    @Test
    public void testParticipantScoreAverageDTO() {
        // TODO: test ParticipantScoreAverageDTO
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'averageScore'
     */
    @Test
    public void averageScoreTest() {
        // TODO: test averageScore
    }

    /**
     * Test the property 'averageRatedScore'
     */
    @Test
    public void averageRatedScoreTest() {
        // TODO: test averageRatedScore
    }

    /**
     * Test the property 'averagePoints'
     */
    @Test
    public void averagePointsTest() {
        // TODO: test averagePoints
    }

    /**
     * Test the property 'averageRatedPoints'
     */
    @Test
    public void averageRatedPointsTest() {
        // TODO: test averageRatedPoints
    }

}
