/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.cit.ase.artemis.sdk.model.GetAllTextSubmissions200ResponseInner;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchResultPageDTOSubmission
 */
public class SearchResultPageDTOSubmissionTest {
    private final SearchResultPageDTOSubmission model = new SearchResultPageDTOSubmission();

    /**
     * Model tests for SearchResultPageDTOSubmission
     */
    @Test
    public void testSearchResultPageDTOSubmission() {
        // TODO: test SearchResultPageDTOSubmission
    }

    /**
     * Test the property 'resultsOnPage'
     */
    @Test
    public void resultsOnPageTest() {
        // TODO: test resultsOnPage
    }

    /**
     * Test the property 'numberOfPages'
     */
    @Test
    public void numberOfPagesTest() {
        // TODO: test numberOfPages
    }

}
