/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.cit.ase.artemis.sdk.model.AttachmentUnit;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Slide
 */
public class SlideTest {
    private final Slide model = new Slide();

    /**
     * Model tests for Slide
     */
    @Test
    public void testSlide() {
        // TODO: test Slide
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'attachmentUnit'
     */
    @Test
    public void attachmentUnitTest() {
        // TODO: test attachmentUnit
    }

    /**
     * Test the property 'slideImagePath'
     */
    @Test
    public void slideImagePathTest() {
        // TODO: test slideImagePath
    }

    /**
     * Test the property 'slideNumber'
     */
    @Test
    public void slideNumberTest() {
        // TODO: test slideNumber
    }

}
