/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.cit.ase.artemis.sdk.model.ProgrammingExercise;
import de.tum.cit.ase.artemis.sdk.model.SubmissionPolicy;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubmissionPenaltyPolicy
 */
public class SubmissionPenaltyPolicyTest {
    private final SubmissionPenaltyPolicy model = new SubmissionPenaltyPolicy();

    /**
     * Model tests for SubmissionPenaltyPolicy
     */
    @Test
    public void testSubmissionPenaltyPolicy() {
        // TODO: test SubmissionPenaltyPolicy
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'submissionLimit'
     */
    @Test
    public void submissionLimitTest() {
        // TODO: test submissionLimit
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'programmingExercise'
     */
    @Test
    public void programmingExerciseTest() {
        // TODO: test programmingExercise
    }

    /**
     * Test the property 'exceedingPenalty'
     */
    @Test
    public void exceedingPenaltyTest() {
        // TODO: test exceedingPenalty
    }

}
