/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import de.tum.cit.ase.artemis.sdk.model.Feedback;
import de.tum.cit.ase.artemis.sdk.model.TextBlock;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TextAssessmentDTO
 */
public class TextAssessmentDTOTest {
    private final TextAssessmentDTO model = new TextAssessmentDTO();

    /**
     * Model tests for TextAssessmentDTO
     */
    @Test
    public void testTextAssessmentDTO() {
        // TODO: test TextAssessmentDTO
    }

    /**
     * Test the property 'textBlocks'
     */
    @Test
    public void textBlocksTest() {
        // TODO: test textBlocks
    }

    /**
     * Test the property 'feedbacks'
     */
    @Test
    public void feedbacksTest() {
        // TODO: test feedbacks
    }

}
