/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.api;

import de.tum.cit.ase.artemis.sdk.*;
import de.tum.cit.ase.artemis.sdk.auth.*;
import de.tum.cit.ase.artemis.sdk.model.PlagiarismComparisonObject;
import de.tum.cit.ase.artemis.sdk.model.PlagiarismComparisonStatusDTO;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlagiarismResourceApi
 */
public class PlagiarismResourceApiTest {

    private final PlagiarismResourceApi api = new PlagiarismResourceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePlagiarismComparisonsTest() throws ApiException {
        //Long exerciseId = null;
        //Long plagiarismResultId = null;
        //Boolean deleteAll = null;
        //api.deletePlagiarismComparisons(exerciseId, plagiarismResultId, deleteAll);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlagiarismComparisonForSplitViewTest() throws ApiException {
        //Long courseId = null;
        //Long comparisonId = null;
        //PlagiarismComparisonObject response = api.getPlagiarismComparisonForSplitView(courseId, comparisonId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePlagiarismComparisonStatusTest() throws ApiException {
        //Long courseId = null;
        //Long comparisonId = null;
        //PlagiarismComparisonStatusDTO plagiarismComparisonStatusDTO = null;
        //api.updatePlagiarismComparisonStatus(courseId, comparisonId, plagiarismComparisonStatusDTO);
        // TODO: test validations
    }

}
