/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.cit.ase.artemis.sdk.api;

import de.tum.cit.ase.artemis.sdk.*;
import de.tum.cit.ase.artemis.sdk.auth.*;
import de.tum.cit.ase.artemis.sdk.model.LoginVM;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserJwtControllerApi
 */
public class UserJwtControllerApiTest {

    private final UserJwtControllerApi api = new UserJwtControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authorizeTest() throws ApiException {
        //String userAgent = null;
        //LoginVM loginVM = null;
        //api.authorize(userAgent, loginVM);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authorizeSAML2Test() throws ApiException {
        //String body = null;
        //api.authorizeSAML2(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        //api.logout();
        // TODO: test validations
    }

}
